### ISSUE TITLE
TST-02 - Caso de Teste da classe ContaEspecial (ContaEspecialTest)

### ISSUE THREAD

**Issue by zdsantos** [TPII20152/SB05#6]
- [x] **1. Cenário de Teste - Creditar Normal (testCreditarNormal):** crie um teste que verifique se a operação creditar() está funcionando corretamente, para isso, escolha como entrada um valor positivo, execute a operação creditar() e verifique se o saldo da conta foi acrescido do valor esperado;
- [x] **2. Cenário de Teste - Creditar Negativo (testCreditarNegativo):** crie um  teste que verifique se a operação creditar() está funcionando corretamente, para isso, escolha como entrada um negativo, execute a operação creditar() e verifique se o saldo resultante da conta permanece o mesmo de antes da execução da operação;
- [x] **3. Cenário de Teste - Bônus Normal (testBonusNormal):**   crie    um teste    que verifique se    a   operação  de creditar() está incrementando o bônus corretamente, para isso, escolha como entrada um valor positivo, execute a operação creditar() e verifique se o bônus da conta foi acrescido  do valor    esperado (i.e., acrescido   de 0,01 do valor creditado);
- [x] **4. Cenário de Teste - Bônus Negativo  (testBonusNormal):** crie um    teste   que verifique se a operação   de creditar() está incrementando o bônus corretamente, para isso, escolha  como entrada um valor negativo, execute a operação creditar() e verifique    se o    bônus da   conta permanece o mesmo de antes    da execução da operação;
- [x] **5. Cenário de Teste – Render Bônus (testRendeBonus):** crie um  teste    que    verifique se a operação de rendeBonus() está rendendo o bônus corretamente, para isso, realize operações de crédito na conta a fim de    incrementar o   valor    dos     bônus, que é incrementado em 0,01 do valor creditado em cada operação de crédito. Após isso, verifique   a quantidade de bônus acumulados (obterBonus()) e, em seguida, execute a operação rendeBonus() e verifique se o saldo da conta foi   acrescido   da quantidade   de bônus   acumulada.

**Comment by karenraiany** [comment]
Finalizado

**Comment by thiagoisaias** [comment]
Karen!
Vc deu push na master haha
A sua branch TST-02 ficou pra trás.

Não?

**Comment by zdsantos** [comment]
Testes testCreditarNegativo() e testBonusNegativo() não estão passando.

**Comment by karenraiany** [comment]
Não estão passando, por isso vou criar uma issue de bug...
